# GameSquare
  ## top row
GameSquare.create(spaceNumber: 21, name: "freeParking", funds: 0)
GameSquare.create(spaceNumber: 22, name: "kentuckyAve", buyable: true, price: 220, owned: false, buildable: true, builtOn: false, pricePerHouse: 150, rent: 18, oneHouse: 90, twoHouse: 250, threeHouse: 700, fourHouse: 875, hotel: 1050)
GameSquare.create(spaceNumber: 23, name: "sharkTank")
GameSquare.create(spaceNumber: 24, name: "indianaAve", buyable: true, price: 240, owned: false, buildable: true, builtOn: false, pricePerHouse: 150, rent: 18, oneHouse: 90, twoHouse: 250, threeHouse: 700, fourHouse: 875, hotel: 1050)
GameSquare.create(spaceNumber: 25, name: "illinoisAve", buyable: true, price: 240, owned: false, buildable: true, builtOn: false, pricePerHouse: 150, rent: 20, oneHouse: 100, twoHouse: 300, threeHouse: 750, fourHouse: 925, hotel: 1100)
GameSquare.create(spaceNumber: 26, name: "boRailroad", buyable: true, price: 200, owned: false, buildable: false, rent: 25)
GameSquare.create(spaceNumber: 27, name: "atlanticAve", buyable: true, price: 260, owned: false, buildable: true, builtOn: false, pricePerHouse: 150, rent: 22, oneHouse: 110, twoHouse: 330, threeHouse: 800, fourHouse: 975, hotel: 1150)
GameSquare.create(spaceNumber: 28, name: "ventnorAve", buyable: true, price: 260, owned: false, buildable: true, builtOn: false, pricePerHouse: 150, rent: 22, oneHouse: 110, twoHouse: 330, threeHouse: 800, fourHouse: 975, hotel: 1150)
GameSquare.create(spaceNumber: 29, name: "waterWorks", buyable: true, price: 150, owned: false, buildable: false, desc: "If a player owns either, rent is equal to the amount shown on the dice times 4. If a player owns both, rent is equal to the amount shown on the dice times 10.")
GameSquare.create(spaceNumber: 30, name: "marvinGardens", buyable: true, price: 280, owned: false, buildable: true, builtOn: false, pricePerHouse: 150, rent: 24, oneHouse: 120, twoHouse: 360, threeHouse: 850, fourHouse: 1025, hotel: 1200  )
GameSquare.create(spaceNumber: 31, name: "goToJail")
  ## middle rows
GameSquare.create(spaceNumber: 20, name: "newYorkAve", buyable: true, price: 200, owned: false, buildable: true, builtOn: false, pricePerHouse: 100, rent: 16, oneHouse: 80, twoHouse: 220, threeHouse: 600, fourHouse: 800, hotel: 1000)
GameSquare.create(spaceNumber: 32, name: "pacificAve", buyable: true, price: 300, owned: false, buildable: true, builtOn: false, pricePerHouse: 200, rent: 26, oneHouse: 130, twoHouse: 390, threeHouse: 900, fourHouse: 1100, hotel: 1275)
GameSquare.create(spaceNumber: 19, name: "tennesseeAve", buyable: true, price: 180, owned: false, buildable: true, builtOn: false, pricePerHouse: 100, rent: 14, oneHouse: 70, twoHouse: 200, threeHouse: 550, fourHouse: 750, hotel: 950)
GameSquare.create(spaceNumber: 33, name: "northCarolinaAve", buyable: true, price: 300, owned: false, buildable: true, builtOn: false, pricePerHouse: 200, rent: 26, oneHouse: 130, twoHouse: 390, threeHouse: 900, fourHouse: 1100, hotel: 1275)
GameSquare.create(spaceNumber: 18, name: "ventureFund")
GameSquare.create(spaceNumber: 34, name: "ventureFund",)
GameSquare.create(spaceNumber: 17, name: "stJamesPlace", buyable: true, price: 180, owned: false, buildable: true, builtOn: false, pricePerHouse: 100, rent: 14, oneHouse: 70, twoHouse: 200, threeHouse: 550, fourHouse: 750, hotel: 950)
GameSquare.create(spaceNumber: 35, name: "pennAve", buyable: true, price: 320, owned: false, buildable: true, builtOn: false, pricePerHouse: 200, rent: 28, oneHouse: 150, twoHouse: 450, threeHouse: 100, fourHouse: 1200, hotel: 1400)
GameSquare.create(spaceNumber: 16, name: "pennRailroad", buyable: true, price: 200, owned: false, buildable: false, rent: 25)
GameSquare.create(spaceNumber: 36, name: "shortLineRailroad", buyable: true, price: 200, owned: false, buildable: false, rent: 25)
GameSquare.create(spaceNumber: 15, name: "virginiaAve", buyable: true, price: 160, owned: false, buildable: true, builtOn: false, pricePerHouse: 100, rent: 12, oneHouse: 60, twoHouse: 180, threeHouse: 500, fourHouse: 700, hotel: 900)
GameSquare.create(spaceNumber: 37, name: "sharkTank")
GameSquare.create(spaceNumber: 14, name: "statesAve", buyable: true, price: 140, owned: false, buildable: true, builtOn: false, pricePerHouse: 100, rent: 10, oneHouse: 50, twoHouse: 150, threeHouse: 450, fourHouse: 625, hotel: 750)
GameSquare.create(spaceNumber: 38, name: "parkPlace", buyable: true, price: 350, owned: false, buildable: true, builtOn: false, pricePerHouse: 200, rent: 35, oneHouse: 275, twoHouse: 500, threeHouse: 1100, fourHouse: 1300, hotel: 1500)
GameSquare.create(spaceNumber: 13, name: "electricCompany", buyable: true, price: 150, owned: false, buildable: false, desc: "If a player owns either, rent is equal to the amount shown on the dice times 4. If a player owns both, rent is equal to the amount shown on the dice times 10.")
GameSquare.create(spaceNumber: 39, name: "luxuryTax", price: -200, desc: "Pay $75.")
GameSquare.create(spaceNumber: 12, name: "stCharlesPlace", buyable: true, price: 140, owned: false, buildable: true, builtOn: false, pricePerHouse: 100, rent: 10, oneHouse: 50, twoHouse: 150, threeHouse: 450, fourHouse: 625, hotel: 750)
GameSquare.create(spaceNumber: 40, name: "boardWalk", buyable: true, price: 400, owned: false, buildable: true, builtOn: false, pricePerHouse: 200, rent: 50, oneHouse: 200, twoHouse: 600, threeHouse: 1400, fourHouse: 1700, hotel: 2000)
  ## bottom row
GameSquare.create(spaceNumber: 11, name: "inJail")
GameSquare.create(spaceNumber: 10, name: "connecticutAve", buyable: true, price: 120, owned: false, buildable: true, builtOn: false, pricePerHouse: 50, rent: 8, oneHouse: 40, twoHouse: 100, threeHouse: 300, fourHouse: 450, hotel: 600)
GameSquare.create(spaceNumber: 9, name: "vermontAve", buyable: true, price: 100, owned: false, buildable: true, builtOn: false, pricePerHouse: 50, rent: 6, oneHouse: 30, twoHouse: 90, threeHouse: 270, fourHouse: 400, hotel: 550)
GameSquare.create(spaceNumber: 8, name: "sharkTank")
GameSquare.create(spaceNumber: 7, name: "orientalAve", buyable: true, price: 100, owned: false, buildable: true, builtOn: false, pricePerHouse: 50, rent: 6, oneHouse: 30, twoHouse: 90, threeHouse: 270, fourHouse: 400, hotel: 550)
GameSquare.create(spaceNumber: 6, name: "readingRailroad", buyable: true, price: 200, owned: false, buildable: false, rent: 25)
GameSquare.create(spaceNumber: 5, name: "incomeTax", price: -200, desc: "Pay 10% or $200, whichever is higher.")
GameSquare.create(spaceNumber: 4, name: "balticAve", buyable: true, price: 60, owned: false, buildable: true, builtOn: false, pricePerHouse: 50, rent: 4, oneHouse: 20, twoHouse: 60, threeHouse: 180, fourHouse: 320, hotel: 450)
GameSquare.create(spaceNumber: 3, name: "ventureFund")
GameSquare.create(spaceNumber: 2, name: "mediterraneanAve", buyable: true, price: 60, owned: false, buildable: true, builtOn: false, pricePerHouse: 50, rent: 2, oneHouse: 10, twoHouse: 30, threeHouse: 90, fourHouse: 160, hotel: 250)
GameSquare.create(spaceNumber: 1, name: "Go",)

# VentureFundard
  VentureFundCard.create(desc: "Advance To Go; Collect $200.")
  VentureFundCard.create(desc: "Bank error in your favor. Collect $200.")
  VentureFundCard.create(desc: "Doctor's fees. Pay $50.")
  VentureFundCard.create(desc: "From sale of stock you get $50.")
  VentureFundCard.create(desc: "Get out of jail free. This card may be kept until used.")
  VentureFundCard.create(desc: "Go to jail. Do not pass GO. Do not collect $200.")
  VentureFundCard.create(desc: "Grand Opera Night. Collect $50 from every player for opening seats.")
  VentureFundCard.create(desc: "Holiday Funds Mature. Receive $100.")
  VentureFundCard.create(desc: "Income tax refund. Collect $20.")
  VentureFundCard.create(desc: "It's your birthday! Collect $10 from every player.")
  VentureFundCard.create(desc: "Life insurance matures. Collect $100.")
  VentureFundCard.create(desc: "Hospital Fees. Pay $50.")
  VentureFundCard.create(desc: "School fees. Pay $50.")
  VentureFundCard.create(desc: "Receive $25 consultancy fee.")
  VentureFundCard.create(desc: "You have won second prize in a beauty contest. Collect $10.")
  VentureFundCard.create(desc: "You inherit $100")

# SharkTankard
  SharkTankCard.create(desc: "Advance To Go; Collect $200.")
  SharkTankCard.create(desc: "Advance to illinoisAve. If you pass GO collect $200.")
  SharkTankCard.create(desc: "Advance to stCharlesPlace. If you pass GO collect $200.")
  SharkTankCard.create(desc: "Advance token to nearest utility. If owned, pay owner twice rent.")
  SharkTankCard.create(desc: "Advance token to nearest railRoad. If owned, pay owner twice as much rent.")
  SharkTankCard.create(desc: "Banks pays you dividend of $50.")
  SharkTankCard.create(desc: "Get out of jail free.")
  SharkTankCard.create(desc: "Go back three spaces.")
  SharkTankCard.create(desc: "Go to Jail. Do not pass GO. Do not collect $200.")
  SharkTankCard.create(desc: "Make general repairs on all your properties. For each house pay $25. For each hotel payC $100.")
  SharkTankCard.create(desc: "Pay poort tax of $15.")
  SharkTankCard.create(desc: "Take a trip to reading railRoad. If you pass go, collect $200.")
  SharkTankCard.create(desc: "Take a walk on the boardWalk.")
  SharkTankCard.create(desc: "You have been elected chairman of the board. Pay each player $50.")
  SharkTankCard.create(desc: "Your building loan matures. Receive $150.")
  SharkTankCard.create(desc: "You have won a crossword competition. Collect $100.")

puts 'created seeds successfully'